version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: car_shop
      POSTGRES_USER: car_shop1
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "5433:5432"
