# Generated by Django 4.2.6 on 2023-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название машины')),
                ('age', models.DateTimeField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет машины')),
                ('transmission', models.CharField(choices=[('Автомат', 'Автомат'), ('Механика', 'Механика'), ('Вариатор', 'Вариатор')], default='Механика', max_length=10, verbose_name='Выбор трансмисси')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('engine', models.CharField(choices=[('Дизель', 'Дизель'), ('Гибрид', 'Гибрид'), ('Бензин', 'Бензин'), ('Электро', 'Электро'), ('Газ', 'Газ')], default='Бензин', max_length=50, verbose_name='Вид двигателя')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Обьем двигателя')),
                ('vile_side', models.CharField(choices=[('Леворульный', 'Леворульный'), ('Праворульный', 'Праворульный')], default='Леворульный', max_length=50, verbose_name='Расположение руля')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Пробег')),
                ('condition', models.CharField(choices=[('Новое', 'Новое'), ('Старое', 'Старое'), ('Идеальное', 'Идеальное'), ('Аварийное', 'Аварийное')], default='Нет', max_length=50, verbose_name='Состояние')),
            ],
        ),
    ]
