# Generated by Django 4.2.6 on 2023-10-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Автомат', 'Автомат'), ('Механика', 'Механика'), ('Вариатор', 'Вариатор')], default='Механика', max_length=10, verbose_name='Выбор трансмиссии'),
        ),
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Обьем двигателя'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product.car')),
            ],
            options={
                'verbose_name': 'Фото машины',
                'verbose_name_plural': 'Фото машин',
            },
        ),
    ]
